### ISSUE TITLE
Process Section Interaction not obvious

### ISSUE THREAD

**Issue by hallidude** [OpenMined/openmined-website#12]
The visuals on in this section are fantastic. One issue that users might have at first glance is that the other sections that come after 'Create' might not be obvious. Is there a way we could hint that there's more content and the 'Distribute', 'Train' etc sections are also clickable? What do you guys think?

**Comment by hallidude** [comment]
Maybe along the lines of 
![interaction - process section](https://user-images.githubusercontent.com/3579610/33890116-4aca6b70-df78-11e7-9265-8963602b6b3d.png)
(This is a very rough prototype)

**Comment by cereallarceny** [comment]
I feel this process is fairly intuitive already.  Closing for now.
