### ISSUE TITLE
Include the OpenMined Team Members Map link on the site

### ISSUE THREAD

**Issue by lucaslopes** [OpenMined/openmined-website#15]
It would be nice to have a link on the, maybe the footer, of the website to our [Members Map](https://openmined.github.io/Team-Map/)

**Comment by cereallarceny** [comment]
I would agree.  In the design we actually have a user map that's a little bit better designed to integrate into the footer.  It will be done eventually, but you're on the right track.  Let's put this on hold for now, but we'll eventually want to.

**Comment by cereallarceny** [comment]
The members map would likely want to be embedded within the website in a cleaner, better-integrated fashion.  It's not likely to appear as a link anywhere.  Closing for now until a better implementation is detailed.
