### ISSUE TITLE
Reduce Line Length

### ISSUE THREAD

**Issue by HelpMeGitGud** [OpenMined/openmined-website#17]
Some lines on the site are more than 150 characters long. The [material design guideline on typography](https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines) quotes an advice from the Baymard Institute: 

> You should have around 60 characters per line if you want a good reading experience. Having the right amount of characters on each line is key to the readability of your text.

**Comment by cereallarceny** [comment]
This is relative and pedantic.
