### ISSUE TITLE
Loading image does not load initialy

### ISSUE THREAD

**Issue by robert-wagner** [OpenMined/openmined-website#40]
When loading a new page the loading image does not load immediately which results in the words openmined spinning. The image loads when the page is almost loaded.

**Comment by cereallarceny** [comment]
Yep, noticed this today.  I've hidden the alt tag for the time being to minimize the damage.  Would love to find a fix for this.

**Comment by robert-wagner** [comment]
Looks much better with the alt tag hidden.

**Comment by cereallarceny** [comment]
Still ugly, but that mitigates the issues for now.  Would love any contributions on this.

**Comment by cereallarceny** [comment]
This is fixed in 56a843f24f3aaaec1795ee84a645bfefddb48dd6
