### ISSUE TITLE
"Brand Guide" PDF is blocked by AdBlock on OpenMined site.

### ISSUE THREAD

**Issue by matthew-mcateer** [OpenMined/openmined-website#57]
After scrolling to the very bottom of the main page (https://www.openmined.org/, as of April 17th, 2018), and clicking on the "Brand Guide" link, it goes to the following link:

https://www.openmined.org/assets/openmined-brand-guide.pdf

However, initially on this page, I only see the rainbow backdrop used by the rest of the OpenMined website, and nothing else. The label for the tab in the browser is also "Page Not Found | OpenMined". The URL has `pdf` at the end, but no downloads start.

However, when I turned off Adblock, the PDF was suddenly visible. I believe this is the first time this has ever happened when opening a PDF document in Chrome. Considering that AdBlock (https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom) is literally one of the most-used chrome extensions out there, perhaps fixing this incompatibility should be on the TODO list.

**Comment by cereallarceny** [comment]
Hey @matthew-mcateer - thanks for the report.  Would you mind opening the Chrome Inspector and unregistering the service worker?  This could be related to an old issue which is still propagated if you viewed the site a while back.

In the Chrome Inspector, navigate to "Application" then to "Clear storage".  Make sure everything is checked and then hit the "Clear site data" button at the bottom of the window.  From there, do a hard refresh and hopefully, the PDF should work.  If not, we'll leave the issue open.

**Comment by matthew-mcateer** [comment]
Yep! Thanks @cereallarceny ! It's working now!
