### ISSUE TITLE
Change "Secure aggregation for federated learning" from "in progress" to "done"!

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/openmined-website#72]
We have accomplished another sub-bullet on our milestones! (https://github.com/OpenMined/PySyft/issues/1502)

**Comment by cereallarceny** [comment]
@iamtrask What other items at this point should be marked as "completed" or "in progress"?

**Comment by farnazkhorsand** [comment]
Where can I find the corresponding Demo?
The Demo title: [Federated Learning with Secure Aggregation Demo]
 #1545
