### ISSUE TITLE
Brand Guide button leads to a "Page not found" but the link works fine

### ISSUE THREAD

**Issue by SneakyAsH311** [OpenMined/openmined-website#75]
- The page link https://www.openmined.org/assets/openmined-brand-guide.pdf works fine 

- the links to the Brand Guide on the www.openmined.org homepage however give a page not found 

- The link that it sends you to is the correct link and works when you refresh the page, but initially you get a page not found screen

**Comment by cereallarceny** [comment]
This is a known caching issue.  I'm going to close this for now as we will likely switch up our caching strategy in near future releases of the website.
