### ISSUE TITLE
Watch Intro btn linking missing video

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/openmined-website#76]
This button links to a missing video on YouTube -> do we want to link to another video or to the Udacity lectures?
![Uploading Capture d’écran 2019-07-08 à 21.18.29.png…]()

**Comment by LaRiffle** [comment]
<img width="1238" alt="btn" src="https://user-images.githubusercontent.com/12446521/60959188-10e4b280-a308-11e9-9b7c-e37bd0c2926e.png">

**Comment by cereallarceny** [comment]
Removed and deployed.
