### ISSUE TITLE
Brand guide link doesn't work properly

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/openmined-website#79]
If you click on the "Brand guide" btn at the bottom of the main page you get a 404; if you refresh you get correctly access to:
https://www.openmined.org/assets/openmined-brand-guide.pdf

**Comment by Yugandhartripathi** [comment]
Same problem for the "Brand Guide" link in nav bar.

**Comment by Yugandhartripathi** [comment]
@cereallarceny Even after new deployment this issue is not resolved

**Comment by cereallarceny** [comment]
It's a caching issue I have no control over without renaming the file itself.  What do you need it for?

**Comment by Yugandhartripathi** [comment]
I don't need it for anything specific. I just thought that it's a bug that needs fixing because it's not intuitive to reload after opening a page that says 404 for someone who might want to access the brand guide pdf but if it's a caching issue and we got no control then I guess it can't be helped.

**Comment by replomancer** [comment]
@cereallarceny
I believe a quick fix is adding "#" at the end of the URL like this:
```
https://www.openmined.org/assets/openmined-brand-guide.pdf#
```
In my tests it makes the link work as expected. I don't know if there's a better fix.
