### ISSUE TITLE
Possibly Wrongful Explanation under [SECURE] Section : "Insecure"

### ISSUE THREAD

**Issue by syyunn** [OpenMined/openmined-website#80]
Following is the page-description in openmined-website :

[SECURE]
"OpenMined is building tools that allow models to be trained within insecure, distributed environments such as end user devices. We aim to support two methods of secure computation: multi-party computation and homomorphic encryption."

I think the word "insecure" needs to be replaced with the word "secure".

**Comment by Yugandhartripathi** [comment]
@syyunn No, afaik it's correct. In my understanding it says "Sending models and training on end user devices(that are distributed and insecure) can usually risk Model params, IP etc but using SMPC and encryption openmined allows you to do that in a safe way"

**Comment by cereallarceny** [comment]
Deployed new copy.
