### ISSUE TITLE
Map in the footer doesn't always show member coordinates

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/openmined-website#87]
The map should show up like this:

<img width="1080" alt="Screen Shot 2019-11-14 at 6 42 51 PM" src="https://user-images.githubusercontent.com/1297930/68886184-993bef80-070e-11ea-9dce-be31dcbd2086.png">

But it often shows up like this:

<img width="1259" alt="Screen Shot 2019-11-14 at 6 43 14 PM" src="https://user-images.githubusercontent.com/1297930/68886206-a48f1b00-070e-11ea-9b82-1664bd452e03.png">

Figure out why!  :)

Hint: it works locally, but doesn't work consistently when deployed.  I have a feeling this has to do with the component not triggering a new render when the data comes in from the statistics API.

**Comment by bogomil** [comment]
Can we close this? It's not relevant anymore/
