### ISSUE TITLE
Slack invite is no longer working

### ISSUE THREAD

**Issue by gautamkrishnar** [OpenMined/openmined-website#93]
## Description
The slack invite is no longer working, http://slack.openmined.org/

## How to Reproduce
1. Go to https://www.openmined.org/
2. Click on Chat on slack button

## Expected Behavior
Invite should work

## Screenshots
<img width="1438" alt="Screenshot 2020-11-13 at 7 29 46 PM" src="https://user-images.githubusercontent.com/8397274/99079972-a839d400-25e6-11eb-9d7b-87981cc5718f.png">

**Comment by cereallarceny** [comment]
Fixed
