### ISSUE TITLE
No mention of new course website on homepage

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/openmined-website#94]
Hi, 
The **Learn Private AI** button on the homepage links to the old Udacity course. 
For organic discoverability it would be great if a link to the new course platform were added on the homepage.
Or has the link not been added on purpose?

**Comment by cereallarceny** [comment]
Fixed https://github.com/OpenMined/openmined-website/commit/8f5e486adf45dabdab55f0a818cc039e8a19298f
